name: GrimAC
version: 2.1.1
main: ac.grim.grimac.GrimAC
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - Essentials
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
api-version: 1.13
load: POSTWORLD
permissions:
  grim.alerts:
    description: Receieve alerts for violations
    default: op
  grim.performance:
    description: Check performance metrics
    default: op
  grim.profile:
    description: Check user profile
    default: op
  grim.brand:
    description: Show client brands on join
    default: op