name: False positive
description: Report a false positive here
labels: ["false positive"]
body:
  - type: textarea
    attributes:
      label: Describe the false positive and how to replicate it
      description: |
        Video is always useful. /grim log is required for reporting simulation falses.
        Use /grim verbose and /grim log to get the debug information.
        For non-simulation falses, a minimally reproducable description is best.
      placeholder: |
        1. Join with ???.
        2. Try to ???.
        3. See ??? false flags.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Grim version
      description: |
        Git commit or the version in the jar's name
      placeholder: 'e.g. 2.3.13 OR 41edf0b'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Server version
      description: |
        Run `/version` on your server and paste the full, unmodified output here.
      placeholder: 'This server is running ??? version ??? (MC: ???) (Implementing API version ???)'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugins
      description: |
        List all plugins running on your server. To list plugins, run `/plugins`.
      placeholder: 'Plugins (3): MyOwnCustomPlugin, ViaVersion, GrimAC'
    validations:
      required: true