name: "Question"
description: "Ask us a question"
title: "My Question"
labels: ["question"]
assignees: ["MWHunter"]
body:
- type: markdown
  id: read-the-wiki
  attributes:
    label: "Have you read the Wiki first?"
    description: "Most questions are likely already answered on our Wiki. Please view the Wiki before asking here."
- type: textarea
  id: question
  attributes:
    label: "Question"
    description: "Write your question, clearly and concisely."
    placeholder: "How do I accomplish XYZ? I've tried A, B and C, to no avail."
  validations:
    required: true
