# config.yml - GrimAC 主要配置
# 源代码链接: https://github.com/MWHunter/Grim
# 版权所有 © 2025 DefineOutside 及贡献者 / 遵循 GPLv3 开源协议
# 修改过的二进制文件，或带有复制的Grim代码的插件，必须是私有仓库，不得公开售卖此插件。
# 中文翻译提供 Regotly / nuym / Dg32z_ / tjshtqwq , 如有错误请提交 Issues 并@我们

alerts:
    # 除了向有权限的玩家发送作弊vl外，是否还在控制台中打印作弊vl消息？
    print-to-console: true
    # 是否在其他子服中发送控制台的作弊信息
    # 如果正在使用Velocity，你必须在Velocity的配置中启用` bungee-plugin-message-channel `。
    proxy:
        # 作弊消息是否应该发送到连接到代理的子服?
        send: false
        # 此服务器是否接收来自其他子服的作弊消息？
        receive: false

verbose:
    # 是否在控制台中打印verbose信息
    print-to-console: false
# 是否检查更新
check-for-updates: true

client-brand:
    # 这意味着如果客户端型号匹配以下正则表达式，它将不会将其客户端版本显示在聊天栏中
    ignored-clients:
        - "^vanilla$"
        - "^fabric$"
        - "^quilt$"
        - "^lunarclient:v\\d+\\.\\d+\\.\\d+-\\d{4},(?:fabric|forge)$"
        - "^Feather Fabric$"
        - "^labymod$"
    # Grim 将把包含内置攻击距离修改功能的特定 Forge 版本列入黑名单（Forge 1.18.2 至 1.19.3） 可能会导致1.18.2-1.19.3的Forge版本玩家无法进入服务器。
    # 将此选项设置为 false 将允许上述客户端连接服务器。禁用此选项需自行承担风险（建议打开）。
    disconnect-blacklisted-forge-versions: true

spectators:
    # 将拥有 grim.spectator 权限的人进行隐藏,不管他是否在观察玩家
    hide-regardless: false
    # 观察者在这些世界不会隐藏
    allowed-worlds:
        - ""

# 在玩家无法接收 GrimAC 的 transaction 数据包后,多少秒对玩家进行踢出
# 默认踢出原因为: disconnect.timeout
# 玩家超时踢出时间（单位：秒）（默认 = 60）
max-transaction-time: 60

# 启用此选项可禁止Grim取消接收到的Pong包。
# 可能会优化和其他反作弊的兼容性，但可能会与数据包限制器冲突
# 在你不知道你在干什么的情况下，不要启用。
disable-pong-cancelling: false

# 是否应禁用默认的方块重新同步处理程序？
# 默认情况下，Grim 会从服务器世界读取方块并将它们发送给客户端以修复不同步问题。
# 如果您使用通过数据包创建虚假方块（在服务器世界中不存在）的插件，
# 您应将其设置为 true，以防止 Grim用空气/真实方块覆盖它们。
# 除非通过 API 提供了自定义处理程序，否则这将强制使用 "NoOp"（无操作）处理程序。
disable-default-resync-handler: false

# 是否对重复的移动数据包进行撤销?
# 这可以修复 "bucket desync"（桶不同步问题）. https://bugs.mojang.com/browse/MC-12363,不过Mojang已经在1.21修复了这个问题
# 这仅仅适用于1.8服务器中使用1.17-1.20.5版本的玩家
cancel-duplicate-packet: true

# 是否忽视重复的数据包中的玩家转头
ignore-duplicate-packet-rotation: false

Simulation:
    # 这个检查通过仿真玩家的移动，并与玩家的实际移动进行比较
    # 仿真出的位置（玩家理应到达的位置）和玩家实际位置的偏差（距离）即为移动优势。

    # 当玩家合法时，我们应该将总移动优势乘以多少
    # 这是默认配置的样子（x 轴 = seconds ，y 轴 = 1/1000 方块）: https://www.desmos.com/calculator/d4ufgxrxer
    setback-decay-multiplier: 0.999
    # 最大允许玩家移动优势的阈值（单位：方块）
    # 已经内置了Optifine FastMath的三角函数表，设置为0.001可避免FastMath误判
    # 若玩家移动优势大于此阈值，标记玩家作弊
    threshold: 0.001
    # 若玩家的移动优势超过此值，玩家会被强制回弹
    # 假设作弊者的移动优势为0.12，且设置的是0.1，0.12 >= 0.1，玩家会立即被回弹到本应到达的位置
    # -1 关闭此项
    immediate-setback-threshold: 0.1
    # 若玩家的总移动优势超过此值，玩家会被强制回弹
    # 假设作弊者1个游戏刻的移动优势为0.11，并且违规了10次（10个游戏刻），即0.11*10，为1.1
    # 若设置的值为1，1.1 >= 1，那么玩家会立即被回弹到本应到达的位置
    # -1 关闭此项
    max-advantage: 1
    # 在默认配置的50秒后，玩家的总优势将从4个方块变为1个方块
    # 这是默认配置的样子（x 轴 = seconds ，y 轴 = 1/1000 方块）: https://www.desmos.com/calculator/4lovswdarj

    # 若玩家的总移动优势大于此项，则会被重置为此项
    # 例如：总移动优势为4.2，会被强制重置到4
    # 这是为了防止玩家的总移动优势过大，并且永远无法清除总移动优势
    max-ceiling: 4
    # 设置回弹的违规等级阈值
    # 1 为旧行为
    setback-violation-threshold: 1

# 检查玩家是否穿墙
Phase:
    setbackvl: 1 # 错误的方块可以允许爬墙，加上这个检查是相对稳定的
    decay: 0.005

AirLiquidPlace:
    cancelvl: 0

FabricatedPlace:
    cancelvl: 5

FarPlace:
    cancelvl: 5

PositionPlace:
    cancelvl: 5

RotationPlace:
    cancelvl: 5

# 使用模拟移动进行的NoSlow(使用物品时不会减速)检查
# 在这里解释错误的服务器代码......即使在发送垃圾数据包时右键单击和副手按钮也很分辨
# 比其他反作弊更稳定，但请报告任何错误......我在这里修复了大量的代码问题。
NoSlow:
    # 最大允许玩家在使用物品时的移动优势（单位：方块）
    # 启用 NoSlow 后，标记量持续为 0.03-0.2
    threshold: 0.001
    # 到达多少VL时回弹
    setbackvl: 5
    # 当玩家使用一个物品并被它减慢时衰减多少VL
    decay: 0.05

Knockback:
    # 当玩家合法时，我们应该将总优势乘以多少
    setback-decay-multiplier: 0.999
    # 最大允许玩家的移动优势（单位：方块）
    threshold: 0.001
    # 若玩家的总移动优势超过此值，玩家会被强制回弹
    # 假设作弊者1个游戏刻的移动优势为0.11，并且违规了10次（10个游戏刻），即0.11*10，为1.1
    # 若设置的值为1，1.1 >= 1，那么玩家会立即被回弹到本应到达的位置
    # -1 关闭此项
    immediate-setback-threshold: 0.1
    # 若玩家的总移动优势超过此值，玩家会被强制回弹
    # 假设作弊者1个游戏刻的移动优势为0.11，并且违规了10次（10个游戏刻），即0.11*10，为1.1
    # 若设置的值为1，1.1 >= 1，那么玩家会立即被回弹到本应到达的位置
    # -1 关闭此项
    max-advantage: 1
    # 若玩家的总移动优势大于此项，则会被重置为此项
    # 例如：总移动优势为4.2，会被强制重置到4
    # 这是为了防止玩家的总移动优势过大，并且永远无法清除总移动优势
    max-ceiling: 4


Explosion:
    threshold: 0.001
    # 若玩家的总移动优势超过此值，玩家会被强制回弹
    # 假设作弊者1个游戏刻的移动优势为0.11，并且违规了10次（10个游戏刻），即0.11*10，为1.1
    # 若设置的值为1，1.1 >= 1，那么玩家会立即被回弹到本应到达的位置
    # -1 关闭此项
    setbackvl: 3
    # 到达多少VL时回弹

TimerA:
    setbackvl: 10
    drift: 120
    # 玩家卡顿时，可以累积以供以后使用的时间（单位：毫秒）
    # 如果设置得太高，可能会允许 1.8版本的快速使用/快速回血/快速射弓绕过，120毫秒似乎是一个很好的平衡

# 此项是config是用来防止玩家移动与实时差距过大，来限制对 TimerA 平衡机制的滥用。
TimerLimit:
    # 在检查玩家的延迟时对timer balance进行限制, 防止滥用
    # 在合法玩家的延迟超过这个延迟阈值时可能会造成误拉回
    # 填写-1则关闭
    ping-abuse-limit-threshold: 1000

NegativeTimer:
    # 玩家的移动丢失了多少毫秒？
    drift: 1200

# 与 TimerA 相同的检查方法，但适用于坐骑
VehicleTimer:
    # 实体的1.0005Timer 检查
    setbackvl: 10
    # VL达到多少时回弹？

PacketOrderI:
    # 如果玩家因使用1.7动画模组而误判，则启用此项
    exempt-placing-while-digging: false

Reach:
    threshold: 0.0005
    # 我们应该将实体碰撞箱扩大多少？ 0.0005 应该检测到 3.0005+ reach
    #
    # 在 1.9-1.18.1（不是 1.18.2）或某些客户端/服务器组合中存在 0.03 距离的增加，因为
    # 协议更改和限制。 对于 1.8 服务器上的 1.7/1.8 客户端，此检查功能最为强大。
    block-impossible-hits: true
    # 我们应该取消不合法的攻击吗？
    # 攻击距离为3.00-3.03可能不会被取消，但仍会被作弊标记，因为有数据包顺序限制
    enable-post-packet: false
    # 这将在每个游戏刻（tick）结束时发送一个额外的数据包，以检查更多的作弊
    # 这会注入服务器的连接列表以在服务器刷新之前发送最终数据
    # 启用这将增加所有玩家的带宽占用
    # 但这不会降低整体服务器性能
    # 启用此功能将检查到更多作弊者。
    # 禁用此功能仍会检查到作弊者，不会导致误报
    # 除非你是专注于1.8版本的PvP服务器，否则不建议使用这个额外的数据包

exploit:
    allow-sprint-jumping-when-using-elytra: true
    # 是否允许玩家在使用鞘翅时候进行的疾跑跳跃
    allow-building-on-ghostblocks: true
    # 该选项可在发生假方块时重新同步玩家方块，并允许玩家在假方块上继续放置方块
    distance-to-check-if-ghostblocks: 2
    # 检查假方块的距离。
    # 范围限制为 2 到 4

# 启用在加入时注入 netty 的日志插件以调试兼容性问题
debug-pipeline-on-join: false

# 启用实验性检查
experimental-checks: false

# 取消有问题的格挡
reset-item-usage-on-item-update: true
reset-item-usage-on-attack: true
reset-item-usage-on-slot-change: true
reset-item-usage-on-item-use: true

# Grim有时会取消非法的数据包，比如Timer。
# 在一秒钟内取消了多少个数据包后，我们应该踢掉这个玩家？
# 我们认为你应该启用此项，因为有些数据包限制器并不记录被Grim取消的数据包。
packet-spam-threshold: 100
# 启用此项可在玩家因 packet-spam-threshold 被踢时打印堆栈追踪
debug-packet-cancel: false

# 在玩家处于非飞行状态，且ping（延迟）大于多少毫秒后，Grim会踢出这个玩家？
# 填写-1则关闭
max-ping-out-of-flying: 1000

# 当玩家使用鞘翅飞行，且ping（延迟）大于多少毫秒后，Grim会取消这个玩家正在使用的烟花火箭？
# 可以避免高延迟玩家使用一个烟花火箭就可以一直飞行
# 填写-1则关闭
max-ping-firework-boost: 1000

history:
    enabled: true
    # 使用 /grim history <player> 时每页显示多少条记录
    entries-per-page: 15
    # history命令中应该插入的服务器名称是什么？如果多个服务器共用同一数据库，这个选项会很有用
    server-name: Prison
    database:
        # 本地存储使用SQLITE，如有外部数据库请使用MYSQL或POSTGRESQL。此设置仅在服务器重启时更新
        type: SQLITE
        # 数据库连接信息
        host: localhost
        port: 3306
        database: grim
        username: root
        password: ""
# 不要调整这个
config-version: 9
