name: Gradle Package (Development)

on:
    workflow_dispatch:
        inputs:
            run-build-scan:
                description: 'Run with public build scan (adds --scan)'
                required: true
                type: boolean
                default: false
    push:
        branches:
            - 'main'
            - '2.0'
            - 'dev'
            - 'release'
            - 'release/**'
        paths:
            - '.github/workflows/**'
            - 'buildSrc/**'
            - 'bukkit/**'
            - 'common/**'
            - 'fabric/**'
            - '**.java'
            - '**.kt'
            - '**.kts'
            - '**.toml'

jobs:
    call-build-workflow:
        uses: ./.github/workflows/build-and-publish.yml
        with:
            is-release-build: false
            release-version-type: alpha
            run-build-scan: ${{ github.event.inputs.run-build-scan == 'true' }}
        secrets:
            BUILD_UPDATE_TOKEN: ${{ secrets.BUILD_UPDATE_TOKEN }}
            BUILD_UPDATE_URL: ${{ secrets.BUILD_UPDATE_URL }}
